# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 11:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiterappwebview', '0002_auto_20170804_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('orderJSON', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
