# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('waiterappwebview', '0003_activeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeorder',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
